//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgGateway.ADAPT.Representation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RepresentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepresentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgGateway.ADAPT.Representation.RepresentationResources", typeof(RepresentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap-shot of the ISO 11783-11 online data base
        ///@ Copyright International Organization for Standardization, see: www.iso.org/iso/copyright.htm. No reproduction on networking 
        ///permitted without license from ISO. The export file from the online data base is supplied without liability. Hard and Saved 
        ///copies of this document are considered uncontrolled and represents a snap-shot of the ISO11783-11 online data base.
        ///
        ///
        ///DD Entity: 0 Data Dictionary Version
        ///Definition: This DDE is used to specify which version of t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ddiExport {
            get {
                return ResourceManager.GetString("ddiExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by Mike Waldo (private) --&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;RepresentationSystem.xslt&quot;?&gt;
        ///&lt;RepresentationSystem xmlns=&quot;urn:schemas-johndeere-com:Representation&quot; xmlns:bt=&quot;urn:schemas-johndeere-com:BasicTypes&quot; xmlns:unit=&quot;urn:schemas-johndeere-com:UnitSystem&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:schemas-johndeere-com:Representation RepresentationSyste [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RepresentationSystem {
            get {
                return ResourceManager.GetString("RepresentationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by Mike Waldo (private) --&gt;
        ///&lt;UnitSystem xmlns=&quot;urn:schemas-johndeere-com:UnitSystem&quot; xmlns:bt=&quot;urn:schemas-johndeere-com:BasicTypes&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:schemas-johndeere-com:UnitSystem UnitSystem.xsd&quot;&gt;
        ///	&lt;SchemaVersion major=&quot;1&quot; minor=&quot;5&quot;/&gt;
        ///	&lt;ContentVersion major=&quot;1&quot; minor=&quot;47&quot;/&gt;
        ///	&lt;SupportedLanguages&gt;
        ///		&lt;Language&gt;en&lt;/Language&gt;
        ///		&lt;Langu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UnitSystem {
            get {
                return ResourceManager.GetString("UnitSystem", resourceCulture);
            }
        }
    }
}
