//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgGateway.ADAPT.Representation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgGateway.ADAPT.Representation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Row&gt;
        ///		&lt;UNRec20&gt;M39&lt;/UNRec20&gt;
        ///		&lt;DomainID&gt;cm1[sec2]-1&lt;/DomainID&gt;
        ///	&lt;/Row&gt;
        ///	&lt;Row&gt;
        ///		&lt;UNRec20&gt;A73&lt;/UNRec20&gt;
        ///		&lt;DomainID&gt;ft1[sec2]-1&lt;/DomainID&gt;
        ///	&lt;/Row&gt;
        ///	&lt;Row&gt;
        ///		&lt;UNRec20&gt;IV&lt;/UNRec20&gt;
        ///		&lt;DomainID&gt;in1[sec2]-1&lt;/DomainID&gt;
        ///	&lt;/Row&gt;
        ///	&lt;Row&gt;
        ///		&lt;UNRec20&gt;M38&lt;/UNRec20&gt;
        ///		&lt;DomainID&gt;km1[sec2]-1&lt;/DomainID&gt;
        ///	&lt;/Row&gt;
        ///	&lt;Row&gt;
        ///		&lt;UNRec20&gt;MSK&lt;/UNRec20&gt;
        ///		&lt;DomainID&gt;m1[sec2]-1&lt;/DomainID&gt;
        ///	&lt;/Row&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DomainIdToUNRec20 {
            get {
                return ResourceManager.GetString("DomainIdToUNRec20", resourceCulture);
            }
        }
    }
}
